name: LiteCommandEditor
version: 1.0.3.0
author: TRC Studio
main: studio.trc.bukkit.litecommandeditor.Main
api-version: 1.13
folia-supported: true
commands:
    litecommandeditor:
        description: Main command of LiteCommandEditor
        aliases: [lce, commandeditor, cmdeditor]